---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/helmfile --version
    register: helmfile_test_output
  - name: helmfile --version
    debug:
      msg: '{{ helmfile_test_output.stdout }}'
