---
- name: Testing andrewrothstein.helmfile
  hosts: all
  tasks:
    - name: Installing andrewrothstein.helmfile
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'helmfile --version'
      ansible.builtin.command: /usr/local/bin/helmfile --version
      changed_when: false
      register: helmfile_test_output
    - name: Output from 'helmfile --version'
      ansible.builtin.debug:
        msg: '{{ helmfile_test_output.stdout }}'
