---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: look for install in {{ helmfile_install_exe }}
  become: true
  stat:
    path: '{{ helmfile_install_exe }}'
  changed_when: false
  register: helmfile_binary
- when: not helmfile_binary.stat.exists
  block:
    - name: downloading {{ helmfile_url }} to {{ helmfile_tmp_archive }}
      become: true
      become_user: root
      get_url:
        url: '{{ helmfile_url }}'
        dest: '{{ helmfile_tmp_archive }}'
        mode: 0644
        checksum: '{{ helmfile_checksum }}'
    - name: mkdir {{ helmfile_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ helmfile_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ helmfile_tmp_archive }} to {{ helmfile_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ helmfile_tmp_archive }}'
        dest: '{{ helmfile_install_dir }}'
        creates: '{{ helmfile_install_exe }}'
  always:
    - name: rm -rf {{ helmfile_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ helmfile_tmp_archive }}'
        state: absent
- name: linking {{ helmfile_link }} to {{ helmfile_install_exe }}
  become: true
  become_user: root
  file:
    src: '{{ helmfile_install_exe }}'
    dest: '{{ helmfile_link }}'
    state: link
