---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Look for install in {{ helmfile_install_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ helmfile_install_exe }}'
  changed_when: false
  register: helmfile_binary
- name: Downloading and installing helmfile
  when: not helmfile_binary.stat.exists
  block:
    - name: Downloading {{ helmfile_url }} to {{ helmfile_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ helmfile_url }}'
        dest: '{{ helmfile_tmp_archive }}'
        mode: '644'
        checksum: '{{ helmfile_checksum }}'
    - name: Mkdir {{ helmfile_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ helmfile_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchive {{ helmfile_tmp_archive }} to {{ helmfile_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ helmfile_tmp_archive }}'
        dest: '{{ helmfile_install_dir }}'
        creates: '{{ helmfile_install_exe }}'
  always:
    - name: Rm -rf {{ helmfile_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ helmfile_tmp_archive }}'
        state: absent
- name: Linking {{ helmfile_link }} to {{ helmfile_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ helmfile_install_exe }}'
    dest: '{{ helmfile_link }}'
    state: link
